### ISSUE TITLE
Add a README with a simple example

### ISSUE THREAD

**Issue by mgaitan** [cam-stitt/factory_boy-peewee#2]
btw, Is this working? How can I use it?  thanks

**Comment by mgaitan** [comment]
I've just found your post http://cam.st/factories-for-peewee-orm/ . Copy/link that as the README, as github is frequently the first searching place.

**Comment by cam-stitt** [comment]
Thanks for pointing that out. It's been a while since I've used this, so hadn't made an effort to update it. For now, I've just put a link to the post. If you wanted to setup a PR with something more there, it would be more than welcome.

**Comment by mgaitan** [comment]
it's fine, thanks
