### ISSUE TITLE
Update pypi package

### ISSUE THREAD

**Issue by ngzhian** [cam-stitt/factory_boy-peewee#3]
https://github.com/cam-stitt/factory_boy-peewee/issues was last updated 2014-10-02, but your repo has been updated to support newer versions of factory_boy. Please push the package to pypi, thanks! @cam-stitt

**Comment by yohanboniface** [comment]
Bump :)

**Comment by cam-stitt** [comment]
I'll do this tonight, promise!

**Comment by cam-stitt** [comment]
Done!
